### ISSUE TITLE
这项目现在是什么状态？

### ISSUE THREAD

**Issue by tonyqus** [HenJigg/CHINA.NET-#2]
如题

**Comment by HenJigg** [comment]
预计在11底内, 先上线一个微信订阅平台。

**Comment by tonyqus** [comment]
这项目不错，我觉得可以一起干，私聊下，用电报吗？

**Comment by tonyqus** [comment]
可能电子书更合适传阅，再加上疫情考虑，但要考虑用户粘性，很多人下完电子书就跟你的小程序说88了。

**Comment by HenJigg** [comment]
其实主要是针对那些买书得人,  有些书也没有电子版, 然后就是, 不用每个人都重复去卖纸质书。
后期他更加会像一个共享社区, 包含借书服务、资料、线下交流会、技术圈子这类得东西。

图书只是一个开始得起点。

________________________________
发件人: Tony Qu <notifications@github.com>
发送时间: 2020年9月29日 2:19
收件人: HenJigg/CHINA.NET- <CHINA.NET-@noreply.github.com>
抄送: 痕迹 <zhouhaogg789@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [HenJigg/CHINA.NET-] 这项目现在是什么状态？ (#2)


可能电子书更合适传阅，再加上疫情考虑，但要考虑用户粘性，很多人下完电子书就跟你的小程序说88了。

―
